// File generated by FlutterFire CLI.
// ---------------------------------------------------------------
// THIS IS A PLACEHOLDER. Do not use these values — they are not
// real credentials. Replace this entire file by running:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// from the project root, after creating a Firebase project and
// connecting it (see README.md, "Firebase setup" section). The CLI
// will overwrite this file with your real project's options for
// each platform you select (Android/iOS/Web).
// ---------------------------------------------------------------

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform. '
          'Run `flutterfire configure` to generate real values.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsjV8Huld_6StmY4UoXdloZ4unGIixUik',
    appId: '1:406166357289:web:8b1d36273e2ecfe0d3e338',
    messagingSenderId: '406166357289',
    projectId: 'diabetes-app-d52fc',
    authDomain: 'diabetes-app-d52fc.firebaseapp.com',
    storageBucket: 'diabetes-app-d52fc.firebasestorage.app',
    measurementId: 'G-TWCX9K603L',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME',
    iosBundleId: 'com.example.diabetesBpApp',
  );
}
